name: photo_spots_app
description: "숨은 사진 스팟 추천 앱 - Flutter scaffold for prototype"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.2.0
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  cached_network_image: ^3.2.3
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.0.0
  image_picker: ^0.8.7
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
